# Spring Boot Application Name
spring.application.name=Learning

# ? PostgreSQL Configuration (INTERNAL for Render)
spring.datasource.url=jdbc:postgresql://dpg-d1eh4695pdvs73c2ha2g-a:5432/studentdb_tnfn
spring.datasource.username=studentdb_tnfn_user
spring.datasource.password=OZv64ALL1E9cbLsh9p6NueUDw0DkQ30o0V
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# HikariCP connection settings (retry if DB is not yet ready)
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.initialization-fail-timeout=60000

# Spring Boot Port
server.port=8080

# Spring Security (Optional)
spring.security.user.name=admin
spring.security.user.password=admin